### ISSUE TITLE
Upcoming XUL removal

### ISSUE THREAD

**Issue by gear54rus** [odin-public/RESTClient-APS#54]
https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/
https://www.change.org/p/mozilla-don-t-remove-xul-and-xpcom-support-from-add-ons
https://www.reddit.com/r/firefox/comments/48a6bu/late_to_the_party_how_will_removing_xul_and_xpcom/

It seems a rewrite is in order. No idea where to get the required man hours for this...

**Comment by mastacheata** [comment]
A full rewrite would definitely be nice (maintainability of this code is absymal to say the least), but isn't neccessary to convert this Extension to WebExt.

There are a few things that need a rewrite, but most of these have a drop in replacement if I'm not mistaken. In order of difficulity/effort needed according to my personal assessment:

- HTTPS Requests are validated using internal nsINSSErrorsService rules. Not sure if that detailed distinction between SSL errors is even needed? And if it is, the error is most likely reported in the XHR error response as well. _(No idea if this even needs a replacement, but if it does, this can be done in a few minutes most)_

- The File import/export functionality relies on nsIFilePicker. For FileUpload one can use the FileReader, for FileDownloads you can use data uris.  _(Estimate: Few minutes - 1 hr)_

- All HttpRequests use nsIXMLHttpRequest instead of plain XMLHttpRequest. The internal interface for HTTP requests is already stuffed with helpers to make it work just like the Standard JS one as far as I can tell. _(I would estimate this can be converted in less than an hour)_

- For OAuth1 the RestClient utilizes functionality from nsICryptoHash to build an SHA1 HMAC, but the same functionality is available in plain JavaScript via the WebCrypto API _(I estimate a few minutes for the SHA1 HMAC replacement, but testing will easily hike this to a couple hours. I've written an OAuth1 client from scratch in PHP a few years ago and it took me more than a week to finally get it all right)_

- A unicode converter (in the hashing code, so that can probably discarded if rewritten to use WebCrypto API) and an UnescapeHTML function _(Honestly no idea about that. Could take anywhere from a couple minutes to hours)_

- The XML Pretty Print thing loads an XML Stylesheet, which in turn refers to an XUL file. I'm sure there's tons of XML pretty print libraries in pure JS/HTML/CSS available. _(Depends on whether it really needs to be ported or not. If it needs to be ported, effort should be limited to researching an XML highlighter just like the one I introduced for JSON last year)_


As far as retaining all features goes, this could easily take a few mandays, but if you can sacrifice a few functions for the time being and focus on what you need for your company's extensions, one should be able to finish the migration in one afternoon.

**Comment by gear54rus** [comment]
> isn't neccessary to convert this Extension to WebExt

Well the old format will be dropped regardless, at the very least we will need to re-pack it using `manifest.json`.

This is a great time to make this thing cross-platform (or cross-browser in that case).

I am currently looking at ARC (https://github.com/jarrodek/ChromeRestClient) extension for Chrome in hopes of adapting it to our needs and porting it to Firefox. It is being semi-actively maintained and it seems like a good next step, let me know what you think.

**Comment by mastacheata** [comment]
ARC is not a Chrome Extensin, but a Chrome App.
Basically they're suffering from the same problems as this extension, because they use some low-level Chrome APIs that won't be available next year.

It looks like the main developer/project owner has already started working on that, but I'm not sure if this is still in the idea state or if he just doesn't want to publish his development progress until finished.

See:
https://github.com/jarrodek/ChromeRestClient/issues/767
https://github.com/jarrodek/ChromeRestClient/issues/1010
https://github.com/jarrodek/ChromeRestClient/issues/1011
https://github.com/jarrodek/ChromeRestClient/issues/1012

**Comment by gear54rus** [comment]
The host extension has been changed: https://github.com/gear54rus/RESTED-APS
